### ISSUE TITLE
The spawner of players that they transfer to the region using create disappear

### ISSUE THREAD

**Issue by DonorKrovi** [thexaero/open-parties-and-claims#105]
As soon as you transfer the spawner with the help of create to the region, they disappear
![image](https://user-images.githubusercontent.com/60231586/193467286-4fdd4c69-0bbf-4901-98af-facf13b42ad5.png)

**Comment by thexaero** [comment]
The way create works is it saves the original position of where you assemble the spawner contraption. When you disassemble it inside your claims, my mod sees it as a contraption coming from from outside (because it is). 
The easiest workaround for this is to unclaim the chunk before turning the contraption into blocks and then reclaiming it.
