### ISSUE TITLE
[1.18.2-0.4.5] Crash due to null entity in `CommonEvents.onMobGrief`

### ISSUE THREAD

**Issue by cdevoogd** [thexaero/open-parties-and-claims#11]
Attached here is the crash report from the server. The null entity is a fireball, and I believe it is from a Ghast in the nether. Once the crash occurred, the entity was stuck and the server would crash immediately after loading into the world. I was able to fix the server by setting forge's config to allowing forge to clear erroring entities for one launch and then turning it back off again. 

[crash-2022-07-07_23.38.32-server.txt](https://github.com/thexaero/open-parties-and-claims/files/9067923/crash-2022-07-07_23.38.32-server.txt)

**Comment by cdevoogd** [comment]
Just ran into this again on the server. Exactly like the first instance, this seems to happen when a player is being shot at by a ghast.

[crash-2022-07-08_02.04.59-server.txt](https://github.com/thexaero/open-parties-and-claims/files/9068361/crash-2022-07-08_02.04.59-server.txt)

**Comment by thexaero** [comment]
Thanks for reporting!
Doesn't happen for me, so I guess some other mod plays a role here too. I just noticed that Forge forwards the owner of the fireball to the mob griefing event and there is no way to get the hit position. Luckily there is separate explosion protection because the mob griefing one is basically useless for ghasts that shoot from outside the claims.
I'll add a null check, which should fix the crash.
