### ISSUE TITLE
Loaded compact machine becomes unloaded when entering mining dimension

### ISSUE THREAD

**Issue by cdevoogd** [thexaero/open-parties-and-claims#13]
I've reproduced this on 0.5.0 and 0.5.1 so far.

I have a setup where I generate power inside of a compact machine, send the power into flux networks, and pull the power out in the overworld. I noticed that when I entered the mining dimension from JAMD, all of my power generation would stop. This seems to be because the compact machine is becoming unloaded, and I can only get power to generate again by manually entering the compact machine again. It's possible that something in the JAMD mod is contributing to this, but I did find that if I load the compact machine with another mod (e.g. Mekanism) it worked fine so I suspect it's a bug here.

I was able to reproduce my setup and this issue with minimal mods on 1.18.2 & Forge 40.1.54:
```
compactmachines-4.3.0.jar
JAMD-1.7.0-build.25+mc1.18.2.jar
Mekanism-1.18.2-10.2.4.464.jar
FluxNetworks-1.18.2-7.0.2.3.jar
jei-1.18.2-9.7.0.209.jar
open-parties-and-claims-forge-1.18.2-0.5.1.jar
```

In this video, you can see that power is being generated fine, but stops once I enter the mining dimension:

https://user-images.githubusercontent.com/15240739/178118987-4caef1db-eb70-4af2-b995-bd4227d734eb.mp4

When the power is stopped, it will restart if I go into the compact machine and load it again:

https://user-images.githubusercontent.com/15240739/178119001-3e3aa657-f98d-4e9d-bfac-90d3e34b94d6.mp4

When I load the chunk with Mekanism instead (using the anchor upgrade), it works just fine.

https://user-images.githubusercontent.com/15240739/178119019-9805c4fc-5348-4b47-8533-d3643f5568ff.mp4

This does not seem to be an issue if the power generation is far away in the overworld:

https://user-images.githubusercontent.com/15240739/178119244-59014db3-d218-4d5e-9a5e-c5b6baead231.mp4

**Comment by thexaero** [comment]
Thanks for reporting!
I'm not entirely sure but I think it's just that forceloading the inside of the machine isn't enough. Everything seems to work fine with regular dimensions. Can you try to also forceload the overworld chunk that pulls the power out?

**Comment by thexaero** [comment]
Really appreciate the videos, btw. Very helpful.

**Comment by cdevoogd** [comment]
> Can you try to also forceload the overworld chunk that pulls the power out?

Even with both sides loaded, the compact machine becomes unloaded. I just re-confirmed this on my modpack server (running 0.5.0) and the minimal instance I used to reproduce and make the videos above (running 0.5.1) and the power still stops.

https://user-images.githubusercontent.com/15240739/178121326-d9039f87-3dad-4b43-a5ec-68e5ffcf614a.mp4

(I believe flux networks takes a second to update so it took once update cycle for it to show the 0 FE/t)

**Comment by thexaero** [comment]
Alright, thanks. I'll test it tomorrow and let you know if I find anything. But most likely forceloading chunks simply isn't enough for this purpose and the anchor upgrade does more than that.

**Comment by thexaero** [comment]
Ok, I've tested everything myself and I don't think it's something on my end. The chunks are not unloaded. If you plant some crops in the machine, exit, go in the mining dimension and back, set random tick speed to 3000, they will grow. The energy flow also doesn't break if it's coming from the plug's buffer.

What I've also noticed is that, using the player config UI, turning forceloading off always stops the energy flow, and, if the energy is coming from the plug's buffer, then turning forceloading back on restores the energy flow. Non-buffer energy flow is not restored by this. Going in the mining dimension and back causes buffer energy to also break if you do a forceload toggle afterwards. Nothing breaks the growing crops though. 

If it's not a Flux or Mekanism bug, then it might be a Forge or a vanilla "bug" because I'm just using the regular ticket system. Although ticking tickets are actually broken in this version of Forge (not in any way that would explain this afaik) and I'm using a workaround. They just recently fixed it, so I'm going to switch to the new version. Let's see if that changes anything.

**Comment by thexaero** [comment]
Nope, the latest Forge version doesn't fix it.

**Comment by cdevoogd** [comment]
Yeah, I think you may be right. It looks like the issue might be stemming directly from Flux Networks rather than this mod. I just went ahead and tested with some other mods like tesseract, and they seem to act normally and stay loaded. I guess that Flux is just struggling with it for some reason.

I'll go ahead and close this for now, thanks for the help!

**Comment by thexaero** [comment]
Alright, gotcha. Thanks for your help as well!
