### ISSUE TITLE
Crash when using tnt x500 from lucky tnt mod

### ISSUE THREAD

**Issue by zkitkatwise** [thexaero/open-parties-and-claims#138]
Also crashes with ftbchunks. No need for the chunk to be claimed.
Forge 40.1.84 on 1.18.2
Doesn't crash if ftbchunks or open parties and claims are not installed.

Crash report:
https://bytebin.lucko.me/CUXS3lHL8o

**Comment by thexaero** [comment]
Thanks for reporting!
I see what's happening. I'll look into it but it might be necessary to completely disable such explosions to protect the claims, not sure at the moment.

**Comment by thexaero** [comment]
Alright. It seems that by the time the Lucky TNT mod fires the explosion event, the damage has already been done. This means that it is not possible to cancel the explosion at that point to protect claims. It's honestly better to just let the server crash because nobody should be using these 2 mods together.
