### ISSUE TITLE
Support with Journeymap

### ISSUE THREAD

**Issue by notIkibo** [thexaero/open-parties-and-claims#163]
FTB Chunks has support with Journeymap, but I really don't like seeing three seperate mods of ftb just for parties and claiming chunks (and it's library)

**Comment by thexaero** [comment]
Whether a map mod supports this mod is not up to this mod, it's up to the map mod or an addon for the map mod to implement it.

**Comment by notIkibo** [comment]
If that is so, I will tell that the devs of Journeymap then, but as a dev yourself, it has a higher chance of implementation than a random user

**Comment by thexaero** [comment]
Sorry, that is not reasonable. I have a lot of other things I'd rather work on than to implement a claim overlay for every map mod in existence and then update it every time a map mod makes significant changes. This mod does not implement the Xaero's minimap and world map mods, it's the other way around, which makes a lot more sense. Rather than this mod (most likely me) having to keep up with 10 constantly updating closed source map mods, it's better if 10 mods implement a single documented open source mod. Implementing a claim map requires a lot more knowledge of the map mod than of this one. You would basically just fetch world claims from here using the API. The dev work is shared and also reduced because of the experience each dev has with a particular map mod.

**Comment by thexaero** [comment]
Now, of course, I could be the one to create a separate addon for Journeymap, but I obviously would rather work on my own map mod.

**Comment by mysticdrew** [comment]
We have an optional plugin style API that would make adding Journeymap support a breeze to add overlays and interacting with the map(clicks, drags, add buttons, add rightclick options, and much more). 

However, maybe a separate integration mod that uses the API from both Journeymap and Open parties and claims to hook them together would be the easiest. Since we do not want to have a dependency of mods that we do not control in Journeymap either. 

https://github.com/TeamJM/journeymap-api/tree/1.19.3_1.9-fabric
https://github.com/TeamJM/journeymap-api/tree/1.19.3_1.9-forge

**Comment by thexaero** [comment]
@mysticdrew Thanks for the info! Yeah, I figured if it was going to happen, it would probably be a separate addon mod. Either way, I'll have to let somebody else work on that. If there's enough interest, it will probably happen soon.

**Comment by mysticdrew** [comment]
@thexaero 
Someone created this for integration
https://github.com/KosmosPrime/journey-pac

**Comment by thexaero** [comment]
@mysticdrew Awesome to see! I'll check it out.
