### ISSUE TITLE
how can i protect players from claiming spawn protected chunks?

### ISSUE THREAD

**Issue by xxr4cc** [thexaero/open-parties-and-claims#184]
i have this server and i want to have a spawn where players cant claim spawn protected chunks
is there anyway to do it or workaround of this feature.

**Comment by samuelh2005** [comment]
Make the server claim the chunks

**Comment by samuelh2005** [comment]
Do this like:
* Become the server with `/openpac-claims server-claim-mode`
* Claim the chunks like normal. Notice how they are owned by the server now.
* Un-become the server with `/openpac-claims server-claim-mode` again.

You do need admin / operator permissions.

**Comment by samuelh2005** [comment]
This also means the vanilla chunk protection **can be disabled**; because Open Parties and Claims do their own protection. This means you can have the spawn protected chunks be whatever shape you like, and any chunk in the world could be claimed by the server too e.g. villages - but this needs to be manually done for all (or with another custom mod).

**Comment by thexaero** [comment]
Exactly what @ajh123 said but I want to also add that you do not necessarily need OP to use server claim mode, there is a FTB Ranks permission that also gives you that ability. Same with admin mode. More permission mod support is planned, for example Lucky Perms.
