### ISSUE TITLE
SUGGESTION: Multiple Separate Claims

### ISSUE THREAD

**Issue by juicebin** [thexaero/open-parties-and-claims#19]
It would be nice to be able to have separate claims. As in, multiple claims owned by one person, but with different configurations.

Or perhaps this could just be a server-specific thing. That way regions can be defined.

**Comment by thexaero** [comment]
Thanks for the suggestion!
I don't think so for each individual player, but I'll consider it for server claims.

**Comment by thexaero** [comment]
I guess I could make it available to individual players as well and make it configurable how many separate claim configs players can have. Might have to move most options in the player config to a new config type. 
Not confirming anything because this can become a serious issue for syncing the claims, but I'll look into it.

**Comment by juicebin** [comment]
Perhaps just being able to identify specific regions within a claim may be better?

**Comment by thexaero** [comment]
Both variants will require roughly the same changes to the system, so I'll go with the one that creates more possibilities.

**Comment by DadoIrie** [comment]
multiple claims for servers might be quite useful ... especially when able to name them ... say there are multiple towns on the server with *obviously* different names and I'd say all players with permission lvl 3 and 4 are required or being part of the trusted member of the server - maybe like a builder - in order to be able to brake and place blocks ... what I mean by that is that it shouldn't be forced having permission lvl3 or 4 in order to be able to build on server claims. (tried really to explain that thorough and hope it makes sense)

multiple claims for individual players might also become handy for them having like a outpost base, but *obviously again* should not be used in order to get more claims when the main claim has used all the claims available and should be counted into the total claims count

**Comment by thexaero** [comment]
@dadoirie Yeah, that's pretty much the idea for multiple claims. 

Server claims can be modified by people in admin-mode, using the command.  So I'm pretty sure permission mods can already give access to this command to non-OPs.

**Comment by thexaero** [comment]
Although I just realized that admin mode gives way more permissions than you'd want to give a builder. I'll think about what can be done for it. For example, could use a new FTB ranks permission.
