### ISSUE TITLE
Crash with Requiem

### ISSUE THREAD

**Issue by ryleu** [thexaero/open-parties-and-claims#195]
With requiem installed (you need to use Quilt instead of Fabric), summon a shell with `/requiem shell create`. The game will crash as openpac attempts to treat the shell as an actual player. I think the way you're detecting players is flawed, though I can't be sure as I'm not familiar with the code base.

**Comment by thexaero** [comment]
Can you post the crash report?

**Comment by ryleu** [comment]
[crash-2023-01-08_17.42.16-server.txt](https://github.com/thexaero/open-parties-and-claims/files/10369671/crash-2023-01-08_17.42.16-server.txt)

**Comment by thexaero** [comment]
Thanks!

**Comment by samuelh2005** [comment]
After looking at the crash myself it looks like `ladysnake.requiem.common.entity.PlayerShellEntity` extends from `baritone.api.fakeplayer.FakeServerPlayerEntity` which probably extends from `Player`. 

**A possible fix for Xaero**
Maybe detect all accounts - then get their player - instead of getting all player entities.

**Comment by ryleu** [comment]
thanks for fixing it so quickly!
