### ISSUE TITLE
Crash with some mods

### ISSUE THREAD

**Issue by FlameFire26** [thexaero/open-parties-and-claims#197]
My game is Minecraft 1.19.2 Fabric, the _Optifine_ and _Optifabric_ are both installed.(And about 20 mods including minimap and worldmap.)
When I try to start the game using HMCL launcher, it crashed without showing the game window. Then the launcher give the crash info.

To rule out the problem of _Forge Config API Port_, I disabled _OPAC_ only let _Forge Config API Port_ on. The game goes no problem.

Then I disabled _Optifine_ (Not included _Optifabric_). No problem, too.

I'm not very good at En and reading logs.

Here is the crash zip, it is all I can provide.

[minecraft-exported-crash-info-2023-01-11T17-22-10.zip](https://github.com/thexaero/open-parties-and-claims/files/10390830/minecraft-exported-crash-info-2023-01-11T17-22-10.zip)

**Comment by thexaero** [comment]
What is the name of the jar file you have for Optifine?

**Comment by FlameFire26** [comment]
It's Optifine_1.19.2_HD_U_H9.jar

(Supplement: OPAC is enabled when I disabled Optifine)

Could it be Optifine or Optifabric's problem?

**Comment by FlameFire26** [comment]
I used to play it on Forge, and these mods with Optifine has no problem.

**Comment by samuelh2005** [comment]
[Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium) and [Iris](https://www.curseforge.com/minecraft/mc-mods/irisshaders) **might** work better for you on Fabric (Use them together). Optifine it self was never intended to be used on Fabric  is self - that's why there's Optifabric which tries it's best to make Opitfine run. Iris is compatible with 99% of Optifine shader packs - and sodium may give you better performance. But you may need to the [Indium](https://www.curseforge.com/minecraft/mc-mods/indium) mod to make some other mods work.

Because Sodium / Iris is open source (Optifine is not) it makes it **simpler for other mods to be made compatible with it**.

**Comment by FlameFire26** [comment]
When I use forge, I put some texture packs in the game. Some of them are Optifine required.

Then I heard about Fabric for assitant mods, so I turn to it and use the strong recommended Sodium and Iris. But Iris(or Sodium) do not support those texture packs, and I'm used to them. So I use Optifabric.

(The texture packs are: UltimaCraft, ColorfulContainers)

**Comment by samuelh2005** [comment]
That's sad.

**Comment by SayoKurokawa** [comment]
I have the same issue.
