### ISSUE TITLE
cannot unclaim

### ISSUE THREAD

**Issue by Dr-WeiAL** [thexaero/open-parties-and-claims#22]
Server admins cannot unclaim chunks of other players

**Comment by thexaero** [comment]
Are you adding "anyway" after the command?

**Comment by Dr-WeiAL** [comment]
Can't cancel on Xaero's minimap or with commands

**Comment by thexaero** [comment]
What do you mean?
You can't do this from the map, but if you go to a chunk and do `/openpac-claims unclaim anyway`, it should work if you're an OP. I think I'll make it automatic when using admin mode, so you'll be able to do this from the map as well.

**Comment by Dr-WeiAL** [comment]
Ok, sorry, I didn't understand what you meant because of the translation software I used. I turned on the administrator mode before, but I couldn't delete chunks. Do you mean to delete the chunks of other players, you can only use the command /openpac-claims unclaim anyway?

**Comment by thexaero** [comment]
Yeah, that is the only way atm.

**Comment by Dr-WeiAL** [comment]
Ok thanks, but one more problem is the player on my server says they can't use anything in a chunk adjacent to another player's chunk, even if that chunk is his own

**Comment by thexaero** [comment]
You can't do some things in a chunk next to another claim, but it's not just anything. You can still place/break/interact with blocks and entities and use things like food and weapons. You can't use buckets though because of how they work.

If their claims are this close, I assume they play together? They should join the same party or both make a party `/openpac-parties create` and add each other as allies `/openpac-parties ally add`. They can then turn off protection against party members or ally parties in the player config (they can open it with a key binding in the controls menu).

**Comment by thexaero** [comment]
If they want to keep protection, they should have 1 chunk between their claims.

**Comment by Dr-WeiAL** [comment]
ok i asked them carefully and they said it is not possible to use fishing rods, barrels in adjacent chunks, then i tested it and most of the mod's items don't work

**Comment by thexaero** [comment]
Yeah, non-block item use is not allowed with a few exceptions for food and weapons.

**Comment by Dr-WeiAL** [comment]
Ok, there should be no other problems for the time being, thank you

**Comment by thexaero** [comment]
No problem and thanks for the feedback.
