### ISSUE TITLE
The mechanism from the Create mod breaks when disassembled in my region.

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#278]
When I assemble a mechanism outside the region and try to figure it out already in my region, when I put it in it completely breaks down.
see video: https://youtu.be/Pc3C195Ukro

**Comment by GitJhopa** [comment]
create:furnace_minecart_contraption

**Comment by thexaero** [comment]
Create contraptions don't have owners. If a contraption enters from outside, it is considered unsafe.
I'll consider attaching the owner in some cases #279.

**Comment by Romaq** [comment]
Added "claims.protection.blocksFromOther" to things players can config, set the default to 3, players already running have been told to set this to 3.

Reran the test... the contraption exploded with none of the blocks it took into the chests. We are heartbroken. :(

Any other workarounds?

**Comment by thexaero** [comment]
@Romaq Chest items not dropping is an issue on Create's end. The same thing happens if you disassemble into bedrock.

**Comment by thexaero** [comment]
I also have no idea what you were trying to do.

**Comment by Romaq** [comment]
Unload the items in a mining contraption without the contraption exploding in a claimed area as seen from @GitJhopa's video at https://youtu.be/Pc3C195Ukro?t=60. My hope is for some setting tweak that would not have a contraption shatter on bringing it back into a claimed chunk as seen in the video.

**Comment by thexaero** [comment]
@Romaq Option 3 does not turn it off. Please edit player configs in-game with the UI screen, not through the files, because it doesn't sound like you are. 
There is not a setting to turn this off without making claim protection completely useless. You want to have protection from contraptions being disassembled into claims, trust me. It is very easy to use it to destroy everything.
To safely disassemble a minecart contraption, turn off your claim protection for 1 second while you disassemble it, then turn it back on.
