### ISSUE TITLE
ic2:mowing_tool breaks foliage in a foreign region when activated.

### ISSUE THREAD

**Issue by GitJhopa** [thexaero/open-parties-and-claims#281]
ic2:mowing_tool breaks foliage in a foreign region when activated.

**Comment by thexaero** [comment]
A lot of bugs that you're reporting are just mods that haven't been made compatible. Things like this are a lot easier to fix on their end by simply firing mod loader events or passing entities to certain methods used (to destroy blocks).
If you want a certain mod to be explicitly supported on my end, you can suggest that instead of reporting every single mod in existence as a bug. You're never going to run out of such mods.
I made a separate issue that describes the request better and am going to close this one.
