### ISSUE TITLE
Crashes when starting up world, 1.20 Fabric

### ISSUE THREAD

**Issue by rainysux** [thexaero/open-parties-and-claims#299]
Most likely incompatibility of a mod? It crashes when trying to open any world. It is able to open the game though. Fabric 1.20n
[crash-2023-07-07_14.00.43-server.txt](https://github.com/thexaero/open-parties-and-claims/files/11986133/crash-2023-07-07_14.00.43-server.txt)

**Comment by mrukas** [comment]
Thats exactly the same error as i get. I tried installing LuckPerms as additional dependency, but this also didn't work.
This problem starts appearing with version b0.18.0. Version b0.17.6 does work correctly with Fabric 1.20.

EDIT: Ok this is pretty interesting. Have you by chance also the Spark mod installed. Because for me everything is working if i disable spark. I'm not sure how spark is interfering with this mod and permissions but it's definitely reproducable.

Maybe @thexaero can help us further investigate this.

**Comment by thexaero** [comment]
Same as #296

**Comment by mrukas** [comment]
Thanks! I also created an issue in the spark repo: https://github.com/lucko/spark/issues/344
