### ISSUE TITLE
Incompatible with Velocity

### ISSUE THREAD

**Issue by skofqq** [thexaero/open-parties-and-claims#466]
The fabric mod does not work correctly when connected to the Velocity lobby. Having a mod on the client does not allow you to connect to the server. For example, one of the log lines: `[00:12:00] [Netty Client IO #1/WARN]: Incorrect key serverConfig.claims.adminModePermission was corrected from null to its default, xaero.pac_admin_mode.`

Velocity: 3.3.0-SNAPSHOT-390
Fabric API: 0.92.1

Full client log: [2024-05-22-1.log](https://github.com/thexaero/open-parties-and-claims/files/15407073/2024-05-22-1.log)

**Comment by thexaero** [comment]
These warning are completely normal and shouldn't break anything. Not sure why you're even seeing them on the client side though. Can I see the server log?

**Comment by thexaero** [comment]
Did you figure it out? @skofqq

**Comment by Valtosin** [comment]
I'm probably having the same problem on the default fabric server in version `1.20.1-0.15.11`, but the configs are reset every time they load or modified. Players can join the game

So, I found a workaround that can temporary fix this issue, just copy your config inside `defaultconfigs` folder and it should "force-overwrite" (or whatever that called) configs and load them properly.

It's possible that this issue is related on the `forgeconfigapiport` library, as I remember.
