### ISSUE TITLE
[Question] Is there a way to get a list of forceloaded chunks that are set by players

### ISSUE THREAD

**Issue by KiwiFlavoredApollo** [thexaero/open-parties-and-claims#529]
Hello, my server is suffering from low TPS and I am looking for a fix. It's a heavily modded server consists of Cobblemon, Create and Farmer's Delight etc. I am aware of `/forceload query` but it does not give me the list of chunks that are set by OPAC.

Here are my questions:

1. Is there a way to get a list of forceloaded chunks?
2. Is there a way to get a list of chunks claimed by other players?
3. Is there a way to disable chunk forceloading?
  I spotted `maxPlayerClaimForceloads = 10` the on the configuration file but I cannot set it to zero according to the documentation.
  
EDIT might be related to https://github.com/thexaero/open-parties-and-claims/issues/233

**Comment by thexaero** [comment]
For 1 and 2, you'll have to view their claim files in the world data using an nbt viewer. By default, only online players are forceloading their chunks, unless you've allowed offline forceloading.

You can set the limit to 0. The config comment says > 0 but really means >= 0. It's not caused by anything on my end, so I can't change that. Make sure to stop the server before changing the main config.
