### ISSUE TITLE
 Differentiation between interaction and block destruction

### ISSUE THREAD

**Issue by Starfire1147** [thexaero/open-parties-and-claims#533]
Please, add two toggles instead of one - one for protection from breaking/destruction of blocks and one for protection from interactions with blocks by hands/items. It is annoying, many mods are using non-standart mechanics, for example, Infinity Buttons (https://modrinth.com/mod/infinitybuttons), Create: Things and Misc (https://modrinth.com/mod/create-misc-and-things) and many more blocks from mods which needs interaction with them by RMB are non-usable inside claimed areas.

**Comment by thexaero** [comment]
Add exceptions through the main config file the same way they're configured for things like doors, buttons, chests. You can even configure a single exception group that includes all block interaction just like what you're suggestion, but it's a horrible idea, which is why it's not available by default. Add exceptions for specific blocks instead.
