### ISSUE TITLE
manage claim visibility

### ISSUE THREAD

**Issue by Otzelix** [thexaero/open-parties-and-claims#568]
Basically an option that allows players/admins to make their claims not globally visible on the world map, as it reveals everybodys base location, You could still have the chunk be showing on the minimap tho.

**Comment by thexaero** [comment]
There is an option to not sync the claims to the client side in the main config file. I'm not going to add a per-player toggle because the mod would still have to sync everything to the client, making the claim data accessible through modified client side anyway. In other words, a visibility toggle would not protect any bases.
