### ISSUE TITLE
Botania spreaders not working in claims correctly.

### ISSUE THREAD

**Issue by ChickenDestroyer** [thexaero/open-parties-and-claims#573]
https://github.com/thexaero/open-parties-and-claims/issues/540#issuecomment-2326936150
Xaero asked me to make a new post, had some life issues so it got delayed.

Botania Mana spreaders are being blocked by server protections.
Specifically its the "Protect Block from Other" setting being set to anything other than off.
This will disable the spreader until it has changed and the spreader has been replaced.
Side issue I noticed, if a beam from a mana spreader hits myself in the claim, it will temp disable it until the spreader gets replaced or jump-started. 

https://github.com/user-attachments/assets/7ced11fd-358f-42a5-be08-4f78ecde7db5

https://github.com/user-attachments/assets/ccc19bce-cdf8-42a5-89f4-968fef2f0a53

https://github.com/user-attachments/assets/8a2c50dd-36ab-45b3-a389-c5e4281bc656

**Comment by ChickenDestroyer** [comment]
With this added:
			entitiesAllowedToGrief = ["minecraft:sheep", "interact$minecraft:potion", "interact$minecraft:trident", "interact$minecraft:(*_|)arrow", "interact$minecraft:ender_pearl", "interact$botania:mana_burst", "interact$minecraft:egg"]

Mana bursts from spreaders/blasters now both can still break blocks and ignore all protections from their bursts.

**Comment by thexaero** [comment]
I see. Really appreciate the videos! So it was exactly what I was thinking after all. The fact that it stops working after failing once is a good thing because it frees some resources (also something I can't prevent on my end). Mana bursts being able to break blocks is exactly why projectile hits are not allowed in claims by default. The "interact$botania:mana_burst" exception should in theory only allow non-break interactions but reality is not that simple. Botania breaks the blocks "anonymously" with removeBlock() instead of providing the projectile as the entity with destroyBlock(). OPAC doesn't and shouldn't protect against anonymous block removals. This makes the default behavior of preventing mana burst hits completely by far the preferred one, as it's better to over-protect than under-.
Proper support for Botania is on the tracker under #485. Although I believe somebody should make an addon before I get to it who knows when. Closing this.

**Comment by ChickenDestroyer** [comment]
Would it be possible to make the "interact$botania:mana_burst" adjustable on a claim by claim basis, in game, with the current limitations of the mod?
